version: '3.8'


services:
  web:
    build: .
    image: 100k.uz
    container_name: 100.uz_con
    command: "sh -c '
    python manage.py makemigrations && 
    python manage.py migrate && python manage.py loaddata products.json categories.json disdricts.json images.json regions.json sellers.json tags.json options.json attrs.json settings.json &&
    python manage.py runserver 0.0.0.0:8001'"
    ports:
      - '8001:8001'
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: pg2
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - pg_data:/var/lib/postgresql/data

  celery:
    build: .
    image: 100k.celery
    container_name: 100k.celery_con
    command: [ "celery", "-A", "DjangoMarket", "worker", "--loglevel=info" ]
    depends_on:
      - rd

  rd:
    image: redis:alpine
    container_name: rd2
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
